# Generated by Django 5.1 on 2024-08-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('person_number', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
