# Generated by Django 5.1 on 2024-08-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lru_web_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="last_name",
        ),
    ]
