# Generated by Django 5.1 on 2024-08-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lru_web_app", "0002_remove_person_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="first_name",
            new_name="name",
        ),
    ]
