# Generated by Django 5.1 on 2024-08-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lru_web_app", "0003_rename_first_name_person_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="person_number",
            new_name="pn",
        ),
    ]
